[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Crunch"
version = "0.1.0"
description = "Crunch PIML package."

[tool.setuptools]
# This tells setuptools to find the 'Crunch' directory
# and treat it as the package.
packages = ["Crunch"]